import { test, expect, beforeEach, afterEach } from "bun:test";
import { join } from "node:path";
import { mkdtemp, rm, mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { nuxt } from "./nuxt.ts";
import type { FileAction, ProjectContext } from "./types.ts";

let tempDir: string;

function makeCtx(overrides?: Partial<ProjectContext>): ProjectContext {
  return {
    cwd: tempDir,
    framework: {
      dep: "nuxt",
      name: "Nuxt",
      sdk: "@clerk/nuxt",
      envVar: "NUXT_PUBLIC_CLERK_PUBLISHABLE_KEY",
      envFile: ".env" as const,
    },
    typescript: true,
    srcDir: false,
    packageManager: "npm",
    existingClerk: false,
    deps: {},
    envFile: ".env",
    ...overrides,
  };
}

function findAction(actions: FileAction[], path: string): FileAction {
  const action = actions.find((a) => a.path === path);
  if (!action) {
    const paths = actions.map((a) => a.path).join(", ");
    throw new Error(`No action found for path "${path}". Available: ${paths}`);
  }
  return action;
}

beforeEach(async () => {
  tempDir = await mkdtemp(join(tmpdir(), "clerk-nuxt-"));
});

afterEach(async () => {
  await rm(tempDir, { recursive: true, force: true });
});

test("scaffolds all actions for a fresh Nuxt project (Nuxt 3 layout)", async () => {
  await Bun.write(
    join(tempDir, "nuxt.config.ts"),
    `export default defineNuxtConfig({
  modules: [],
});
`,
  );

  const plan = await nuxt.scaffold(makeCtx());

  expect(plan.actions).toHaveLength(4);

  const config = findAction(plan.actions, "nuxt.config.ts");
  expect(config.type).toBe("modify");
  if (config.type === "modify") {
    expect(config.content).toContain("@clerk/nuxt");
  }

  // Nuxt 3 layout: pages at pages/ (no app/ directory)
  const signIn = findAction(plan.actions, "pages/sign-in/[...slug].vue");
  expect(signIn.type).toBe("create");
  if (signIn.type === "create") {
    expect(signIn.content).toContain("<template>");
    expect(signIn.content).toContain("SignIn");
  }

  const signUp = findAction(plan.actions, "pages/sign-up/[...slug].vue");
  expect(signUp.type).toBe("create");

  const env = findAction(plan.actions, ".env");
  expect(env.type).toBe("modify");
  if (env.type === "modify") {
    expect(env.content).toContain("NUXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in");
    expect(env.content).toContain("NUXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up");
  }

  expect(plan.postInstructions.length).toBeGreaterThanOrEqual(1);
});

test("scaffolds all actions for a fresh Nuxt project (Nuxt 4 app/ layout)", async () => {
  await Bun.write(
    join(tempDir, "nuxt.config.ts"),
    `export default defineNuxtConfig({
  modules: [],
});
`,
  );
  // Nuxt 4 uses app/ as srcDir by default
  await mkdir(join(tempDir, "app"), { recursive: true });
  await Bun.write(join(tempDir, "app/app.vue"), `<template>\n  <NuxtWelcome />\n</template>\n`);

  const plan = await nuxt.scaffold(makeCtx());

  // app/pages/ for sign-in and sign-up, plus config and env = 4 actions
  // (app.vue replace counts as a 5th)
  const signIn = findAction(plan.actions, "app/pages/sign-in/[...slug].vue");
  expect(signIn.type).toBe("create");
  if (signIn.type === "create") {
    expect(signIn.content).toContain("SignIn");
  }

  const signUp = findAction(plan.actions, "app/pages/sign-up/[...slug].vue");
  expect(signUp.type).toBe("create");
});

test("detects Nuxt 4 layout via app/ directory even without app/app.vue", async () => {
  // Nuxt 4 project where app.vue was deleted or not generated by the template
  await mkdir(join(tempDir, "app/pages"), { recursive: true });
  // No app/app.vue — only the app/ directory exists

  const plan = await nuxt.scaffold(makeCtx());

  const signIn = plan.actions.find((a) => a.path === "app/pages/sign-in/[...slug].vue");
  const signUp = plan.actions.find((a) => a.path === "app/pages/sign-up/[...slug].vue");

  expect(signIn).toBeDefined();
  expect(signUp).toBeDefined();
});

test("skips config when @clerk/nuxt already present", async () => {
  await Bun.write(
    join(tempDir, "nuxt.config.ts"),
    `export default defineNuxtConfig({
  modules: ['@clerk/nuxt'],
});
`,
  );

  const plan = await nuxt.scaffold(makeCtx());

  expect(findAction(plan.actions, "nuxt.config.ts")).toMatchObject({
    type: "skip",
    skipReason: "Already has @clerk/nuxt module",
  });
});

test("skips config when no config file found", async () => {
  const plan = await nuxt.scaffold(makeCtx());

  expect(findAction(plan.actions, "nuxt.config.ts")).toMatchObject({
    type: "skip",
  });
  const action = findAction(plan.actions, "nuxt.config.ts");
  if (action.type === "skip") {
    expect(action.skipReason).toContain("No Nuxt config file found");
  }
});

test("skips auth page when it already exists (Nuxt 3 layout)", async () => {
  await Bun.write(
    join(tempDir, "nuxt.config.ts"),
    `export default defineNuxtConfig({ modules: [] });`,
  );
  await mkdir(join(tempDir, "pages/sign-in"), { recursive: true });
  await Bun.write(
    join(tempDir, "pages/sign-in/[...slug].vue"),
    "<template><div>existing</div></template>",
  );

  const plan = await nuxt.scaffold(makeCtx());

  expect(findAction(plan.actions, "pages/sign-in/[...slug].vue")).toMatchObject({
    type: "skip",
    skipReason: "Sign-in page already exists",
  });
});

test("skips auth page when it already exists (Nuxt 4 app/ layout)", async () => {
  await Bun.write(
    join(tempDir, "nuxt.config.ts"),
    `export default defineNuxtConfig({ modules: [] });`,
  );
  await mkdir(join(tempDir, "app/pages/sign-in"), { recursive: true });
  await Bun.write(join(tempDir, "app/app.vue"), "<template><NuxtPage /></template>");
  await Bun.write(
    join(tempDir, "app/pages/sign-in/[...slug].vue"),
    "<template><div>existing</div></template>",
  );

  const plan = await nuxt.scaffold(makeCtx());

  expect(findAction(plan.actions, "app/pages/sign-in/[...slug].vue")).toMatchObject({
    type: "skip",
    skipReason: "Sign-in page already exists",
  });
});

test("skips env vars when already set", async () => {
  await Bun.write(
    join(tempDir, "nuxt.config.ts"),
    `export default defineNuxtConfig({ modules: [] });`,
  );
  await Bun.write(
    join(tempDir, ".env"),
    `NUXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in\nNUXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up\n`,
  );

  const plan = await nuxt.scaffold(makeCtx());

  expect(findAction(plan.actions, ".env")).toMatchObject({
    type: "skip",
    skipReason: "Sign-in/sign-up route vars already set",
  });
});

test("adds i18n post-instruction when @nuxtjs/i18n detected", async () => {
  await Bun.write(
    join(tempDir, "nuxt.config.ts"),
    `export default defineNuxtConfig({ modules: [] });`,
  );

  const plan = await nuxt.scaffold(makeCtx({ deps: { "@nuxtjs/i18n": "8.0.0" } }));

  expect(plan.postInstructions.some((i) => i.includes("@nuxtjs/i18n"))).toBe(true);
});

test("no i18n instruction without @nuxtjs/i18n", async () => {
  await Bun.write(
    join(tempDir, "nuxt.config.ts"),
    `export default defineNuxtConfig({ modules: [] });`,
  );

  const plan = await nuxt.scaffold(makeCtx({ deps: {} }));

  expect(plan.postInstructions.some((i) => i.includes("@nuxtjs/i18n"))).toBe(false);
});

test("adds auth header in app.vue during bootstrap", async () => {
  await mkdir(join(tempDir, "app"), { recursive: true });
  await Bun.write(
    join(tempDir, "nuxt.config.ts"),
    `export default defineNuxtConfig({
  modules: [],
});
`,
  );
  await Bun.write(
    join(tempDir, "app/app.vue"),
    `<template>
  <div>
    <NuxtRouteAnnouncer />
    <NuxtWelcome />
  </div>
</template>
`,
  );

  const plan = await nuxt.scaffold(makeCtx({ isBootstrap: true, deps: { tailwindcss: "4.0.0" } }));
  const appVue = findAction(plan.actions, "app/app.vue");

  expect(appVue.type).toBe("modify");
  if (appVue.type !== "modify") throw new Error("Expected modify action");

  expect(appVue.content).toContain('<Show when="signed-out">');
  expect(appVue.content).toContain("<SignInButton />");
  expect(appVue.content).toContain("<SignUpButton />");
  expect(appVue.content).toContain('<Show when="signed-in">');
  expect(appVue.content).toContain("<UserButton />");
  expect(appVue.content).toContain("<NuxtPage />");
  expect(appVue.content).toContain(
    'class="flex h-16 items-center justify-end gap-4 border-b px-4"',
  );
  // Nuxt auto-imports — no script setup needed
  expect(appVue.content).not.toContain("<script");
  expect(appVue.description).toContain("auth header");
});

test("does not add auth header for non-bootstrap init", async () => {
  await mkdir(join(tempDir, "app"), { recursive: true });
  await Bun.write(
    join(tempDir, "nuxt.config.ts"),
    `export default defineNuxtConfig({
  modules: [],
});
`,
  );
  await Bun.write(
    join(tempDir, "app/app.vue"),
    `<template>
  <div>
    <NuxtWelcome />
  </div>
</template>
`,
  );

  const plan = await nuxt.scaffold(makeCtx());
  const appVue = findAction(plan.actions, "app/app.vue");

  expect(appVue.type).toBe("modify");
  if (appVue.type !== "modify") throw new Error("Expected modify action");

  expect(appVue.content).toContain("<NuxtPage />");
  expect(appVue.content).not.toContain("<Show");
  expect(appVue.content).not.toContain("<SignInButton");
});

test("omits Show post-instruction when bootstrap includes header", async () => {
  await mkdir(join(tempDir, "app"), { recursive: true });
  await Bun.write(
    join(tempDir, "nuxt.config.ts"),
    `export default defineNuxtConfig({ modules: [] });
`,
  );
  await Bun.write(
    join(tempDir, "app/app.vue"),
    `<template>
  <div>
    <NuxtWelcome />
  </div>
</template>
`,
  );

  const plan = await nuxt.scaffold(makeCtx({ isBootstrap: true }));

  expect(plan.postInstructions.some((i) => i.includes("<Show"))).toBe(false);
});

test("handles nuxt.config.js variant", async () => {
  await Bun.write(
    join(tempDir, "nuxt.config.js"),
    `export default defineNuxtConfig({
  modules: [],
});
`,
  );

  const plan = await nuxt.scaffold(makeCtx());

  const config = findAction(plan.actions, "nuxt.config.js");
  expect(config.type).toBe("modify");
});
