import { test, expect, describe } from "bun:test";
import {
  DEPLOY_COMMAND_DESCRIPTION,
  DEPLOY_COMMAND_SUMMARY,
  INTRO_PREAMBLE,
  bindZoneFile,
  deployComponentLabels,
  deployStatusPendingFooter,
  deployStatusRetryMessage,
  dnsIntro,
  dnsRecords,
  domainAssociationSummary,
  domainsDashboardUrl,
  instanceDashboardUrl,
  nextStepsBlock,
  pendingDnsRecords,
  productionDnsHosts,
} from "./copy.ts";
import type { CnameTarget } from "../../lib/plapi.ts";

const stripAnsi = (value: string): string =>
  value.replace(new RegExp(String.raw`\x1b\[[0-9;]*m`, "g"), "");

describe("bindZoneFile", () => {
  const fixedDate = new Date("2026-05-20T18:30:00.000Z");

  test("renders a BIND fragment with $ORIGIN, $TTL, and one CNAME per target", () => {
    const targets: CnameTarget[] = [
      { host: "clerk.example.com", value: "frontend-api.clerk.services", required: true },
      { host: "accounts.example.com", value: "accounts.clerk.services", required: true },
      {
        host: "clkmail.example.com",
        value: "mail.example.com.nam1.clerk.services",
        required: true,
      },
    ];
    const output = bindZoneFile("example.com", targets, fixedDate);

    expect(output).toContain("; Generated by `clerk deploy` on 2026-05-20T18:30:00.000Z");
    expect(output).toContain(
      "; Import into your existing zone for example.com to add Clerk's required DNS records.",
    );
    expect(output).toContain("$ORIGIN example.com.");
    expect(output).toContain("$TTL 300");
    expect(output).toContain("clerk.example.com.\tIN\tCNAME\tfrontend-api.clerk.services.");
    expect(output).toContain("accounts.example.com.\tIN\tCNAME\taccounts.clerk.services.");
    expect(output).toContain(
      "clkmail.example.com.\tIN\tCNAME\tmail.example.com.nam1.clerk.services.",
    );
    expect(output.endsWith("\n")).toBe(true);
  });

  test("includes optional records (required: false) without filtering", () => {
    const targets: CnameTarget[] = [
      { host: "clerk.example.com", value: "frontend-api.clerk.services", required: true },
      { host: "clk2._domainkey.example.com", value: "dkim2.clerk.services", required: false },
    ];
    const output = bindZoneFile("example.com", targets, fixedDate);

    expect(output).toContain("clerk.example.com.\tIN\tCNAME\tfrontend-api.clerk.services.");
    expect(output).toContain("clk2._domainkey.example.com.\tIN\tCNAME\tdkim2.clerk.services.");
  });

  test("does not double-append the trailing dot when the value already ends with one", () => {
    const targets: CnameTarget[] = [
      { host: "clerk.example.com", value: "frontend-api.clerk.services.", required: true },
    ];
    const output = bindZoneFile("example.com", targets, fixedDate);

    expect(output).toContain("clerk.example.com.\tIN\tCNAME\tfrontend-api.clerk.services.");
    expect(output).not.toContain("frontend-api.clerk.services..");
  });
});

describe("dnsRecords", () => {
  test("labels DKIM (_domainkey) records as email records, not bare CNAME", () => {
    const targets: CnameTarget[] = [
      { host: "clk._domainkey.example.com", value: "dkim1.clerk.services", required: false },
      { host: "clk2._domainkey.example.com", value: "dkim2.clerk.services", required: false },
    ];
    const output = dnsRecords(targets);

    expect(output).toContain("    Host:  clk._domainkey.example.com");
    expect(output).toContain("    Host:  clk2._domainkey.example.com");
    // Both DKIM hosts must carry the email label, not fall through to the
    // generic "CNAME" default (the host's first label is "clk"/"clk2").
    expect(
      output.filter((line) => line.includes("Email (Clerk handles SPF/DKIM automatically)")),
    ).toHaveLength(2);
    expect(output.some((line) => line.trimStart().startsWith("CNAME"))).toBe(false);
  });
});

describe("deployComponentLabels", () => {
  test("returns email DNS in-progress and done labels", () => {
    expect(deployComponentLabels("mail", "example.com")).toEqual({
      progress: "Verifying email DNS records for example.com...",
      done: "Email DNS records verified",
    });
  });

  test("returns dns labels matching the existing dnsVerified string", () => {
    expect(deployComponentLabels("dns", "example.com")).toEqual({
      progress: "Verifying DNS records for example.com...",
      done: "DNS verified for example.com.",
    });
  });

  test("returns ssl labels", () => {
    expect(deployComponentLabels("ssl", "example.com")).toEqual({
      progress: "Issuing SSL certificate for example.com...",
      done: "SSL certificate issued for example.com",
    });
  });
});

describe("deployStatusRetryMessage", () => {
  test("includes current retry count and countdown", () => {
    expect(deployStatusRetryMessage("Verifying DNS records for example.com...", 2, 5, 30)).toBe(
      "Verifying DNS records for example.com... 2/5 attempts, retrying in 30s",
    );
  });
});

describe("nextStepsBlock", () => {
  test("links to the production instance home and its domain settings", () => {
    const output = stripAnsi(nextStepsBlock("app_123", "ins_456", "example.com"));

    expect(output).toContain("Manage this instance in the Clerk Dashboard");
    expect(output).toContain("- Users, settings, and billing:");
    expect(output).toContain("- DNS and SSL status:");
    // The instance root on its own line, not only as a prefix of the domains URL.
    expect(output).toContain("https://dashboard.clerk.com/apps/app_123/instances/ins_456\n");
    expect(output).toContain("https://dashboard.clerk.com/apps/app_123/instances/ins_456/domains");
  });

  test("says the pulled keys go on the host alongside the other Clerk variables", () => {
    // `env pull --instance prod` writes only the two keys. The routing
    // variables `init` wrote have to be carried over by hand, or sign-in
    // silently falls back to the hosted Account Portal.
    const output = nextStepsBlock("app_123", "ins_456", "example.com");

    expect(output).toContain("- Add the same pk_live_/sk_live_ values there.");
    expect(output).toContain("- Also copy the other Clerk variables from your env file");
    expect(output).toContain("NEXT_PUBLIC_CLERK_SIGN_IN_URL");
    expect(output).toContain("writes only the two keys");
  });

  test("ends with a real sign-up on the production domain", () => {
    const output = nextStepsBlock("app_123", "ins_456", "example.com");

    expect(output).toContain("sign up at https://example.com to confirm it works");
  });
});

describe("domainAssociationSummary", () => {
  test("lists every record host the domain will need, including both DKIM hosts", () => {
    // The confirmation screen runs before the instance exists, so this is a
    // prediction from the domain alone. It must match what the create call
    // returns, or the user commits without seeing the full list.
    const output = domainAssociationSummary("example.com").join("\n");

    expect(output).toContain("clerk.example.com");
    expect(output).toContain("accounts.example.com");
    expect(output).toContain("clkmail.example.com");
    expect(output).toContain("clk._domainkey.example.com");
    expect(output).toContain("clk2._domainkey.example.com");
    expect(productionDnsHosts("example.com")).toHaveLength(5);
  });

  test("lead sentence says records are coming, with no record count in it", () => {
    const [lead] = domainAssociationSummary("example.com");

    expect(lead).toContain("Clerk will use these subdomains for");
    // Disclose the obligation before the one-way step without demanding
    // action the user can't take yet.
    expect(lead).toContain("You'll add a DNS record for each after the instance is created:");
    expect(lead).not.toMatch(/\b(three|five|3|5)\b/);
  });

  test("labels the DKIM hosts as email records, not bare CNAMEs", () => {
    const output = domainAssociationSummary("example.com").join("\n");

    expect(output).not.toContain("CNAME  clk._domainkey");
    expect(output).toMatch(/Email .*clk\._domainkey\.example\.com/);
  });
});

describe("dnsIntro", () => {
  test("sets the propagation expectation as minutes, with 48 hours as the outlier", () => {
    const output = dnsIntro("example.com").join("\n");

    expect(output).toContain(
      "usually propagate within minutes, but can occasionally take up to 48 hours",
    );
    expect(output).not.toContain("It can take up to 48 hours");
  });
});

describe("deployStatusPendingFooter", () => {
  const DOMAINS_URL = "https://dashboard.clerk.com/apps/app_1/instances/ins_prod/domains";

  test("reports missing DNS records as not found yet, not as a failure", () => {
    const output = deployStatusPendingFooter(
      "example.com",
      {
        dns: false,
        ssl: false,
        mail: false,
      },
      DOMAINS_URL,
    ).join("\n");

    expect(output).toContain("DNS and email DNS records not found yet for example.com.");
    expect(output).toContain(
      "Add them at your DNS provider, then run `clerk deploy` again to resume.",
    );
    expect(output).toContain("usually takes minutes, but can occasionally take up to 48 hours");
    expect(output).toContain(
      "change the domain in the Clerk Dashboard: https://dashboard.clerk.com/apps/app_1/instances/ins_prod/domains",
    );
    expect(output).not.toContain("still pending");
    expect(output).not.toContain("SSL");
  });

  test("names only the email records when the Frontend API records are verified", () => {
    const output = deployStatusPendingFooter(
      "example.com",
      {
        dns: true,
        ssl: false,
        mail: false,
      },
      DOMAINS_URL,
    ).join("\n");

    // Capitalized at the sentence start; lowercase "email DNS" is only right
    // mid-sentence ("DNS and email DNS").
    expect(output).toContain("Email DNS records not found yet for example.com.");
    expect(output).not.toContain("email DNS records not found");
    expect(output).not.toContain("DNS and email DNS");
  });

  test("says when the record list is missing instead of telling the user to add nothing", () => {
    // DNS unverified but the API returned no targets: "add them" would point
    // at an empty list. One follow-up line, so blank line + sentence.
    const output = deployStatusPendingFooter(
      "example.com",
      { dns: false, ssl: false, mail: false },
      DOMAINS_URL,
      false,
    ).join("\n");

    expect(output).toContain("DNS and email DNS records not found yet for example.com.\n\n");
    expect(output).toContain("Clerk didn't return the list of records to add.");
    expect(output).toContain(
      `Find them on the Domains page in the Clerk Dashboard: ${DOMAINS_URL}`,
    );
    expect(output).toContain("run `clerk deploy` again to resume");
    expect(output).not.toContain("  - ");
    expect(output).not.toContain("Add them at your DNS provider");
  });

  test("tells the user to wait, not act, when only SSL is pending", () => {
    // SSL is Clerk's side; there are no records the user could add.
    const output = deployStatusPendingFooter(
      "example.com",
      {
        dns: true,
        ssl: false,
        mail: true,
      },
      DOMAINS_URL,
    ).join("\n");

    expect(output).toContain("SSL certificate still pending for example.com.");
    expect(output).toContain("run `clerk deploy` again in a few minutes to resume");
    // One follow-up line: a blank line and a sentence, not a one-item list.
    expect(output).toContain("example.com.\n\nClerk issues it");
    expect(output).not.toContain("  - ");
    expect(output).not.toContain("not found yet");
    expect(output).not.toContain("change the domain in the Clerk Dashboard");
  });

  test.each([
    { label: "records pending", status: { dns: false, ssl: false, mail: false } },
    { label: "SSL only pending", status: { dns: true, ssl: false, mail: true } },
    { label: "all components verified", status: { dns: true, ssl: true, mail: true } },
  ])("always says how to resume and that re-running is safe ($label)", ({ status }) => {
    const output = deployStatusPendingFooter("example.com", status, DOMAINS_URL).join("\n");
    expect(output).toMatch(/run `clerk deploy` again.*to resume/i);
    expect(output).toContain("The production instance is already created.");
  });
});

describe("dashboard URLs", () => {
  test("instance URL is the instance root and the domains URL is nested under it", () => {
    expect(instanceDashboardUrl("app_1", "ins_prod")).toBe(
      "https://dashboard.clerk.com/apps/app_1/instances/ins_prod",
    );
    expect(domainsDashboardUrl("app_1", "ins_prod")).toBe(
      "https://dashboard.clerk.com/apps/app_1/instances/ins_prod/domains",
    );
  });
});

describe("INTRO_PREAMBLE", () => {
  test("rules out host-generated URLs as a production domain and says why", () => {
    // Described rather than named: the rule covers every host, and the reject
    // list at the prompt is where specific hosts belong.
    expect(INTRO_PREAMBLE).toContain("The URL a hosting provider generated");
    expect(INTRO_PREAMBLE).toContain("for your deployment won't work here.");
    expect(INTRO_PREAMBLE).not.toMatch(/railway|vercel|netlify/i);
    // Subdomains you control are fine; the old "development subdomain" line
    // read as if they weren't.
    expect(INTRO_PREAMBLE).toContain("app.example.com");
    expect(INTRO_PREAMBLE).not.toContain("development subdomain");
  });
});

describe("DEPLOY_COMMAND_DESCRIPTION", () => {
  test("describes the bare command and the agent-mode report", () => {
    expect(DEPLOY_COMMAND_DESCRIPTION.startsWith(`${DEPLOY_COMMAND_SUMMARY}.`)).toBe(true);
    expect(DEPLOY_COMMAND_DESCRIPTION).toContain("with no subcommand starts an interactive setup");
    expect(DEPLOY_COMMAND_DESCRIPTION).toContain("creates the production instance");
    expect(DEPLOY_COMMAND_DESCRIPTION).toContain("When run by an agent");
    expect(DEPLOY_COMMAND_DESCRIPTION).toContain("`nextAction`");
  });
});

describe("pendingDnsRecords", () => {
  const targets: CnameTarget[] = [
    { host: "clerk.example.com", value: "frontend-api.clerk.services", required: true },
    { host: "accounts.example.com", value: "accounts.clerk.services", required: true },
    {
      host: "clkmail.example.com",
      value: "mail.example.com.nam1.clerk.services",
      required: true,
    },
  ];

  test("returns no records when only SSL remains pending", () => {
    expect(pendingDnsRecords(targets, { dns: true, ssl: false, mail: true })).toEqual([]);
  });

  test("returns only email records when email DNS remains pending", () => {
    const output = pendingDnsRecords(targets, { dns: true, ssl: true, mail: false }).join("\n");

    expect(output).toContain("clkmail.example.com");
    expect(output).not.toContain("clerk.example.com");
    expect(output).not.toContain("accounts.example.com");
  });

  test("returns non-email records when DNS remains pending", () => {
    const output = pendingDnsRecords(targets, { dns: false, ssl: true, mail: true }).join("\n");

    expect(output).toContain("clerk.example.com");
    expect(output).toContain("accounts.example.com");
    expect(output).not.toContain("clkmail.example.com");
  });
});

describe("dnsRecords", () => {
  test("labels DKIM CNAME records as email DNS records", () => {
    const output = dnsRecords([
      { host: "clk._domainkey.example.com", value: "dkim1.clerk.services", required: true },
      { host: "clk2._domainkey.example.com", value: "dkim2.clerk.services", required: true },
    ]).join("\n");

    expect(output).toContain("Email (Clerk handles SPF/DKIM automatically)");
    expect(output).not.toContain("\n  CNAME\n    Type:");
  });
});
