import { test, expect, describe } from "bun:test";
import {
  DEPLOY_COMMAND_DESCRIPTION,
  DEPLOY_COMMAND_SUMMARY,
  INTRO_PREAMBLE,
  bindZoneFile,
  deployComponentLabels,
  deployStatusPendingFooter,
  deployStatusRetryMessage,
  dnsIntro,
  dnsDashboardHandoff,
  dnsRecords,
  domainAssociationSummary,
  domainsDashboardUrl,
  instanceDashboardUrl,
  nextStepsBody,
  pendingCnameTargets,
  productionDnsHosts,
  productionSummary,
} from "./copy.ts";
import type { CnameTarget } from "../../lib/plapi.ts";

const stripAnsi = (value: string): string =>
  value.replace(new RegExp(String.raw`\x1b\[[0-9;]*m`, "g"), "");

describe("bindZoneFile", () => {
  const fixedDate = new Date("2026-05-20T18:30:00.000Z");

  test("renders a BIND fragment with $ORIGIN, $TTL, and one CNAME per target", () => {
    const targets: CnameTarget[] = [
      { host: "clerk.example.com", value: "frontend-api.clerk.services", required: true },
      { host: "accounts.example.com", value: "accounts.clerk.services", required: true },
      {
        host: "clkmail.example.com",
        value: "mail.example.com.nam1.clerk.services",
        required: true,
      },
    ];
    const output = bindZoneFile("example.com", targets, fixedDate);

    expect(output).toContain("; Generated by `clerk deploy` on 2026-05-20T18:30:00.000Z");
    expect(output).toContain(
      "; Import into your existing zone for example.com to add Clerk's required DNS records.",
    );
    expect(output).toContain("$ORIGIN example.com.");
    expect(output).toContain("$TTL 300");
    expect(output).toContain("clerk.example.com.\tIN\tCNAME\tfrontend-api.clerk.services.");
    expect(output).toContain("accounts.example.com.\tIN\tCNAME\taccounts.clerk.services.");
    expect(output).toContain(
      "clkmail.example.com.\tIN\tCNAME\tmail.example.com.nam1.clerk.services.",
    );
    expect(output.endsWith("\n")).toBe(true);
  });

  test("includes optional records (required: false) without filtering", () => {
    const targets: CnameTarget[] = [
      { host: "clerk.example.com", value: "frontend-api.clerk.services", required: true },
      { host: "clk2._domainkey.example.com", value: "dkim2.clerk.services", required: false },
    ];
    const output = bindZoneFile("example.com", targets, fixedDate);

    expect(output).toContain("clerk.example.com.\tIN\tCNAME\tfrontend-api.clerk.services.");
    expect(output).toContain("clk2._domainkey.example.com.\tIN\tCNAME\tdkim2.clerk.services.");
  });

  test("does not double-append the trailing dot when the value already ends with one", () => {
    const targets: CnameTarget[] = [
      { host: "clerk.example.com", value: "frontend-api.clerk.services.", required: true },
    ];
    const output = bindZoneFile("example.com", targets, fixedDate);

    expect(output).toContain("clerk.example.com.\tIN\tCNAME\tfrontend-api.clerk.services.");
    expect(output).not.toContain("frontend-api.clerk.services..");
  });
});

describe("dnsRecords", () => {
  test("labels DKIM (_domainkey) records as email records, not bare CNAME", () => {
    const targets: CnameTarget[] = [
      { host: "clk._domainkey.example.com", value: "dkim1.clerk.services", required: false },
      { host: "clk2._domainkey.example.com", value: "dkim2.clerk.services", required: false },
    ];
    const output = dnsRecords(targets);

    expect(output).toContain("    Host:  clk._domainkey.example.com");
    expect(output).toContain("    Host:  clk2._domainkey.example.com");
    // Both DKIM hosts must carry the email label, not fall through to the
    // generic "CNAME" default (the host's first label is "clk"/"clk2").
    expect(output.filter((line) => line.includes("Email (DKIM)"))).toHaveLength(2);
    expect(output.some((line) => line.trimStart().startsWith("CNAME"))).toBe(false);
  });
});

describe("dnsRecords heading", () => {
  const targets: CnameTarget[] = [
    { host: "clerk.example.com", value: "frontend-api.clerk.services", required: true },
  ];

  test("first hand-over tells the user to add the records", () => {
    expect(dnsRecords(targets)[0]).toBe("Add the following records at your DNS provider:");
  });

  test("after a check that didn't find them, the heading allows that they may already be added", () => {
    expect(dnsRecords(targets, { afterCheck: true })[0]).toBe(
      "Add the following records at your DNS provider if you haven't already:",
    );
  });
});

describe("deployComponentLabels", () => {
  test("returns email DNS in-progress and done labels", () => {
    expect(deployComponentLabels("mail", "example.com")).toEqual({
      progress: "Verifying email DNS records for example.com...",
      done: "Email DNS records verified",
    });
  });

  test("returns dns labels matching the existing dnsVerified string", () => {
    expect(deployComponentLabels("dns", "example.com")).toEqual({
      progress: "Verifying DNS records for example.com...",
      done: "DNS verified for example.com.",
    });
  });

  test("returns ssl labels", () => {
    expect(deployComponentLabels("ssl", "example.com")).toEqual({
      progress: "Issuing SSL certificate for example.com...",
      done: "SSL certificate issued for example.com",
    });
  });
});

describe("deployStatusRetryMessage", () => {
  test("includes current retry count and countdown", () => {
    expect(deployStatusRetryMessage("Verifying DNS records for example.com...", 2, 5, 30)).toBe(
      "Verifying DNS records for example.com... 2/5 attempts, retrying in 30s",
    );
  });
});

describe("nextStepsBody", () => {
  test("links to the production instance home and its domain settings", () => {
    const output = stripAnsi(nextStepsBody("app_123", "ins_456", "example.com", "verified"));

    expect(output).toContain("Manage this instance in the Clerk Dashboard");
    expect(output).toContain("- Users, settings, and billing:");
    expect(output).toContain("- DNS and SSL status:");
    // The instance root on its own line, not only as a prefix of the domains URL.
    expect(output).toContain("https://dashboard.clerk.com/apps/app_123/instances/ins_456\n");
    expect(output).toContain("https://dashboard.clerk.com/apps/app_123/instances/ins_456/domains");
  });

  test("says the pulled keys go on the host alongside the other Clerk variables", () => {
    // `env pull --instance prod` writes only the two keys. The routing
    // variables `init` wrote have to be carried over by hand, or sign-in
    // silently falls back to the hosted Account Portal.
    const output = nextStepsBody("app_123", "ins_456", "example.com", "verified");

    expect(output).toContain("- Add the same pk_live_/sk_live_ values there.");
    expect(output).toContain("- Also copy the other Clerk variables from your env file");
    expect(output).toContain("NEXT_PUBLIC_CLERK_SIGN_IN_URL");
    expect(output).toContain("writes only the two keys");
  });

  test("ends with a real sign-up on the production domain", () => {
    const output = nextStepsBody("app_123", "ins_456", "example.com", "verified");

    expect(output).toContain(
      "3. Redeploy your app, then sign up at https://example.com to confirm it works",
    );
  });

  test("does not send the user to a domain that is not verified yet", () => {
    // After skipping DNS verification the domain doesn't resolve, so step 3
    // has to route through the wizard before the sign-up check.
    const output = nextStepsBody("app_123", "ins_456", "example.com", "pending");

    expect(output).toContain("3. Run `clerk deploy` again once your DNS records are added");
    expect(output).toContain("sign up at https://example.com to confirm it works");
    expect(output).not.toContain("3. Redeploy your app");
  });
});

describe("productionSummary", () => {
  test("only calls production ready once the domain is verified", () => {
    const verified = stripAnsi(productionSummary("example.com", ["Google"], "verified").join("\n"));
    const pending = stripAnsi(productionSummary("example.com", [], "pending").join("\n"));

    expect(verified).toContain("Production ready at https://example.com");
    expect(pending).toContain("Production instance created for https://example.com");
    expect(pending).toContain("Domain      DNS pending");
    expect(pending).not.toContain("Production ready");
  });
});

describe("domainAssociationSummary", () => {
  test("lists every record host the domain will need, including both DKIM hosts", () => {
    // The confirmation screen runs before the instance exists, so this is a
    // prediction from the domain alone. It must match what the create call
    // returns, or the user commits without seeing the full list.
    const output = domainAssociationSummary("example.com").join("\n");

    expect(output).toContain("clerk.example.com");
    expect(output).toContain("accounts.example.com");
    expect(output).toContain("clkmail.example.com");
    expect(output).toContain("clk._domainkey.example.com");
    expect(output).toContain("clk2._domainkey.example.com");
    expect(productionDnsHosts("example.com")).toHaveLength(5);
  });

  test("lead sentence says records are coming, with no record count in it", () => {
    const [lead] = domainAssociationSummary("example.com");

    expect(lead).toContain("Clerk will use these subdomains for");
    // Disclose the obligation before the one-way step without demanding
    // action the user can't take yet.
    expect(lead).toContain(
      "You'll add DNS records for them after the instance is created. The exact list is printed once the instance exists:",
    );
    expect(lead).not.toMatch(/\b(three|five|3|5)\b/);
  });

  test("labels the mail hosts plainly, without the 'Clerk handles it' parenthetical", () => {
    // The lead says the user will add a record for each row; a label saying
    // Clerk handles SPF/DKIM automatically would contradict it on this screen.
    const output = domainAssociationSummary("example.com").join("\n");

    expect(output).toContain("Email           clkmail.example.com");
    expect(output).toContain("Email (DKIM)    clk._domainkey.example.com");
    expect(output).toContain("Email (DKIM)    clk2._domainkey.example.com");
    // Labels pad to one column so the hosts line up.
    expect(output).toContain("Frontend API    clerk.example.com");
    expect(output).toContain("Account portal  accounts.example.com");
    // The server omits the Account portal record when the portal is disabled
    // on the cloned instance, so the lead can't promise one record per row.
    expect(output).toContain(
      "You'll add DNS records for them after the instance is created. The exact list is printed once the instance exists:",
    );
    expect(output).not.toContain("a DNS record for each");
    expect(output).not.toContain("Clerk handles SPF/DKIM");
    expect(output).not.toContain("CNAME  clk._domainkey");
  });
});

describe("dnsIntro", () => {
  test("sets the propagation expectation as minutes, with 48 hours as the outlier", () => {
    const output = dnsIntro("example.com").join("\n");

    expect(output).toContain(
      "usually propagate within minutes, but can occasionally take up to 48 hours",
    );
    expect(output).not.toContain("It can take up to 48 hours");
  });
});

describe("deployStatusPendingFooter", () => {
  const DOMAINS_URL = "https://dashboard.clerk.com/apps/app_1/instances/ins_prod/domains";

  test("reports missing DNS records as not found yet, not as a failure", () => {
    const output = deployStatusPendingFooter(
      "example.com",
      {
        dns: false,
        ssl: false,
        mail: false,
      },
      DOMAINS_URL,
      true,
    ).join("\n");

    expect(output).toContain("DNS and email DNS records not found yet for example.com.");
    // A "Check again" prompt follows this footer, so it points there first and
    // gives the resume command as the fallback.
    expect(output).toContain(
      "Add them at your DNS provider if you haven't already, then choose Check again below.",
    );
    expect(output).toContain("skip for now and run `clerk deploy` later to resume");
    expect(output).toContain("usually takes minutes, but can occasionally take up to 48 hours");
    expect(output).toContain(
      "change the domain in the Clerk Dashboard: https://dashboard.clerk.com/apps/app_1/instances/ins_prod/domains",
    );
    expect(output).not.toContain("still pending");
    expect(output).not.toContain("SSL");
  });

  test("names only the email records when the Frontend API records are verified", () => {
    const output = deployStatusPendingFooter(
      "example.com",
      {
        dns: true,
        ssl: false,
        mail: false,
      },
      DOMAINS_URL,
      true,
    ).join("\n");

    // Capitalized at the sentence start; lowercase "email DNS" is only right
    // mid-sentence ("DNS and email DNS").
    expect(output).toContain("Email DNS records not found yet for example.com.");
    expect(output).not.toContain("email DNS records not found");
    expect(output).not.toContain("DNS and email DNS");
  });

  test("says when the record list is missing instead of telling the user to add nothing", () => {
    // DNS unverified but the API returned no targets: "add them" would point
    // at an empty list. One follow-up line, so blank line + sentence.
    const output = deployStatusPendingFooter(
      "example.com",
      { dns: false, ssl: false, mail: false },
      DOMAINS_URL,
      false,
    ).join("\n");

    expect(output).toContain("DNS and email DNS records not found yet for example.com.\n\n");
    expect(output).toContain("Clerk didn't return the list of records to add.");
    // URL on its own line so terminal autolinkers don't swallow punctuation.
    expect(output).toContain(
      "Find them on the Domains page in the Clerk Dashboard, add them, then choose Check again below.",
    );
    expect(output).toContain(`already created.\n  ${DOMAINS_URL}`);
    expect(output).toContain("run `clerk deploy` later to resume");
    expect(output).not.toContain("  - ");
    expect(output).not.toContain("Add them at your DNS provider");
  });

  test("tells the user to wait, not act, when only SSL is pending", () => {
    // SSL is Clerk's side; there are no records the user could add.
    const output = deployStatusPendingFooter(
      "example.com",
      {
        dns: true,
        ssl: false,
        mail: true,
      },
      DOMAINS_URL,
      true,
    ).join("\n");

    expect(output).toContain("SSL certificate still pending for example.com.");
    expect(output).toContain("choose Check again below in a few minutes");
    expect(output).toContain("run `clerk deploy` later to resume");
    // One follow-up line: a blank line and a sentence, not a one-item list.
    expect(output).toContain("example.com.\n\nClerk issues it");
    expect(output).not.toContain("  - ");
    expect(output).not.toContain("not found yet");
    expect(output).not.toContain("change the domain in the Clerk Dashboard");
  });

  test("says Clerk is still finalizing when every component is verified", () => {
    // The fallthrough branch: all three verified, server hasn't flipped the
    // domain to complete yet. One follow-up line, so blank line + sentence.
    const output = deployStatusPendingFooter(
      "example.com",
      { dns: true, ssl: true, mail: true },
      DOMAINS_URL,
      false,
    ).join("\n");

    expect(output).toContain(
      "Production setup for example.com is still finalizing on Clerk's side.\n\nRun `clerk deploy` again in a few minutes to resume.",
    );
    expect(output).not.toContain("not found yet");
    expect(output).not.toContain("SSL");
  });

  test.each([
    { label: "records pending", status: { dns: false, ssl: false, mail: false }, records: true },
    { label: "records missing", status: { dns: false, ssl: false, mail: false }, records: false },
    { label: "SSL only pending", status: { dns: true, ssl: false, mail: true }, records: false },
    {
      label: "all components verified",
      status: { dns: true, ssl: true, mail: true },
      records: false,
    },
  ])("always says how to resume and that re-running is safe ($label)", ({ status, records }) => {
    const output = deployStatusPendingFooter("example.com", status, DOMAINS_URL, records).join(
      "\n",
    );
    expect(output).toMatch(/run `clerk deploy` (again|later).*to resume/i);
    expect(output).toMatch(/production instance is already created\./i);
  });

  test("omits the Dashboard URL cleanly when no production instance id is known", () => {
    const output = deployStatusPendingFooter(
      "example.com",
      { dns: false, ssl: false, mail: false },
      undefined,
      true,
    ).join("\n");
    expect(output).toContain("change the domain in the Clerk Dashboard.");
    expect(output).not.toContain("undefined");
  });
});

describe("pendingCnameTargets", () => {
  const targets: CnameTarget[] = [
    { host: "clerk.example.com", value: "frontend-api.clerk.services", required: true },
    { host: "clkmail.example.com", value: "mail.clerk.services", required: true },
    { host: "clk._domainkey.example.com", value: "dkim1.clerk.services", required: true },
  ];

  test("returns only the mail targets when only email DNS is unverified", () => {
    const pending = pendingCnameTargets(targets, { dns: true, ssl: true, mail: false });
    expect(pending.map((t) => t.host)).toEqual([
      "clkmail.example.com",
      "clk._domainkey.example.com",
    ]);
  });

  test("returns nothing when only SSL is pending", () => {
    expect(pendingCnameTargets(targets, { dns: true, ssl: false, mail: true })).toEqual([]);
  });
});

describe("dashboard URLs", () => {
  test("instance URL is the instance root and the domains URL is nested under it", () => {
    expect(instanceDashboardUrl("app_1", "ins_prod")).toBe(
      "https://dashboard.clerk.com/apps/app_1/instances/ins_prod",
    );
    expect(domainsDashboardUrl("app_1", "ins_prod")).toBe(
      "https://dashboard.clerk.com/apps/app_1/instances/ins_prod/domains",
    );
  });
});

describe("INTRO_PREAMBLE", () => {
  test("rules out host-generated URLs as a production domain and says why", () => {
    // Described rather than named: the rule covers every host, and the reject
    // list at the prompt is where specific hosts belong.
    expect(INTRO_PREAMBLE).toContain("The URL a hosting provider generated");
    expect(INTRO_PREAMBLE).toContain("for your deployment won't work here.");
    expect(INTRO_PREAMBLE).not.toMatch(/railway|vercel|netlify/i);
    // Subdomains you control are fine; the old "development subdomain" line
    // read as if they weren't.
    expect(INTRO_PREAMBLE).toContain("app.example.com");
    expect(INTRO_PREAMBLE).not.toContain("development subdomain");
  });
});

describe("DEPLOY_COMMAND_DESCRIPTION", () => {
  test("describes the bare command and the agent-mode report", () => {
    expect(DEPLOY_COMMAND_DESCRIPTION.startsWith(`${DEPLOY_COMMAND_SUMMARY}.`)).toBe(true);
    expect(DEPLOY_COMMAND_DESCRIPTION).toContain("with no subcommand starts an interactive setup");
    expect(DEPLOY_COMMAND_DESCRIPTION).toContain("creates the production instance");
    expect(DEPLOY_COMMAND_DESCRIPTION).toContain("When run by an agent");
    expect(DEPLOY_COMMAND_DESCRIPTION).toContain("`nextAction`");
  });
});

describe("dnsRecords", () => {
  test("labels DKIM CNAME records as email DNS records", () => {
    const output = dnsRecords([
      { host: "clk._domainkey.example.com", value: "dkim1.clerk.services", required: true },
      { host: "clk2._domainkey.example.com", value: "dkim2.clerk.services", required: true },
    ]).join("\n");

    expect(output).toContain("Email (DKIM)");
    expect(output).not.toContain("\n  CNAME\n    Type:");
    // Said once under the block, never on a row the user must act on.
    expect(output).toContain(
      "The email records point at Clerk, so you don't need to create SPF or DKIM values yourself.",
    );
    expect(output).not.toMatch(/Email \(DKIM\).*Clerk handles/);
  });

  test("labels the mail host and both DKIM hosts the same way the confirmation screen does", () => {
    // One label set across screens: a host named two ways reads as two records.
    const records = dnsRecords([
      { host: "clkmail.example.com", value: "mail.clerk.services", required: true },
      { host: "clk._domainkey.example.com", value: "dkim1.clerk.services", required: true },
    ]).join("\n");
    const confirmation = stripAnsi(domainAssociationSummary("example.com").join("\n"));

    for (const label of ["Email", "Email (DKIM)"]) {
      expect(records).toContain(label);
      expect(confirmation).toContain(label);
    }
    expect(records).not.toContain("Clerk handles SPF/DKIM automatically");
    expect(confirmation).not.toContain("Clerk handles SPF/DKIM automatically");
  });
});

describe("dnsDashboardHandoff", () => {
  const DOMAINS_URL = "https://dashboard.clerk.com/apps/app_1/instances/ins_prod/domains";

  test("links the Domains page and says how to resume if the check is skipped", () => {
    const output = dnsDashboardHandoff("example.com", DOMAINS_URL, { oauthNext: true }).join("\n");

    expect(output).toContain(`Clerk Dashboard:\n  ${DOMAINS_URL}`);
    // "wizard" appears nowhere else the user can see, so it isn't introduced here.
    expect(output).not.toContain("wizard");
    expect(output).toContain(
      "Next you'll set up OAuth, then this command checks that these records have taken effect.",
    );
    expect(output).toContain("run `clerk deploy` again later to finish");
    // "skip and finish" read as though skipping completed the deploy.
    expect(output).not.toContain("skip and finish");
  });

  test("does not promise an OAuth step when none is coming", () => {
    // On resume OAuth already ran, and a fresh run with no providers skips it.
    // Under a checklist showing OAuth done, "you'll set up OAuth" was wrong.
    const output = dnsDashboardHandoff("example.com", DOMAINS_URL, { oauthNext: false }).join("\n");

    expect(output).toContain("Next, this command checks that these records have taken effect.");
    expect(output).not.toContain("set up OAuth");
    expect(output).toContain("run `clerk deploy` again later to finish");
  });

  test("ends the sentence cleanly when no Dashboard URL is known", () => {
    const output = dnsDashboardHandoff("example.com", undefined, { oauthNext: true }).join("\n");

    expect(output).toContain("on the Domains page in the Clerk Dashboard.");
    expect(output).not.toContain("undefined");
  });
});
