import { test, expect, describe } from "bun:test";
import {
  bindZoneFile,
  deployComponentLabels,
  deployStatusRetryMessage,
  dnsRecords,
  nextStepsBlock,
  pendingDnsRecords,
} from "./copy.ts";
import type { CnameTarget } from "../../lib/plapi.ts";

describe("bindZoneFile", () => {
  const fixedDate = new Date("2026-05-20T18:30:00.000Z");

  test("renders a BIND fragment with $ORIGIN, $TTL, and one CNAME per target", () => {
    const targets: CnameTarget[] = [
      { host: "clerk.example.com", value: "frontend-api.clerk.services", required: true },
      { host: "accounts.example.com", value: "accounts.clerk.services", required: true },
      {
        host: "clkmail.example.com",
        value: "mail.example.com.nam1.clerk.services",
        required: true,
      },
    ];
    const output = bindZoneFile("example.com", targets, fixedDate);

    expect(output).toContain("; Generated by `clerk deploy` on 2026-05-20T18:30:00.000Z");
    expect(output).toContain(
      "; Import into your existing zone for example.com to add Clerk's required DNS records.",
    );
    expect(output).toContain("$ORIGIN example.com.");
    expect(output).toContain("$TTL 300");
    expect(output).toContain("clerk.example.com.\tIN\tCNAME\tfrontend-api.clerk.services.");
    expect(output).toContain("accounts.example.com.\tIN\tCNAME\taccounts.clerk.services.");
    expect(output).toContain(
      "clkmail.example.com.\tIN\tCNAME\tmail.example.com.nam1.clerk.services.",
    );
    expect(output.endsWith("\n")).toBe(true);
  });

  test("includes optional records (required: false) without filtering", () => {
    const targets: CnameTarget[] = [
      { host: "clerk.example.com", value: "frontend-api.clerk.services", required: true },
      { host: "clk2._domainkey.example.com", value: "dkim2.clerk.services", required: false },
    ];
    const output = bindZoneFile("example.com", targets, fixedDate);

    expect(output).toContain("clerk.example.com.\tIN\tCNAME\tfrontend-api.clerk.services.");
    expect(output).toContain("clk2._domainkey.example.com.\tIN\tCNAME\tdkim2.clerk.services.");
  });

  test("does not double-append the trailing dot when the value already ends with one", () => {
    const targets: CnameTarget[] = [
      { host: "clerk.example.com", value: "frontend-api.clerk.services.", required: true },
    ];
    const output = bindZoneFile("example.com", targets, fixedDate);

    expect(output).toContain("clerk.example.com.\tIN\tCNAME\tfrontend-api.clerk.services.");
    expect(output).not.toContain("frontend-api.clerk.services..");
  });
});

describe("dnsRecords", () => {
  test("labels DKIM (_domainkey) records as email records, not bare CNAME", () => {
    const targets: CnameTarget[] = [
      { host: "clk._domainkey.example.com", value: "dkim1.clerk.services", required: false },
      { host: "clk2._domainkey.example.com", value: "dkim2.clerk.services", required: false },
    ];
    const output = dnsRecords(targets);

    expect(output).toContain("    Host:  clk._domainkey.example.com");
    expect(output).toContain("    Host:  clk2._domainkey.example.com");
    // Both DKIM hosts must carry the email label, not fall through to the
    // generic "CNAME" default (the host's first label is "clk"/"clk2").
    expect(
      output.filter((line) => line.includes("Email (Clerk handles SPF/DKIM automatically)")),
    ).toHaveLength(2);
    expect(output.some((line) => line.trimStart().startsWith("CNAME"))).toBe(false);
  });
});

describe("deployComponentLabels", () => {
  test("returns email DNS in-progress and done labels", () => {
    expect(deployComponentLabels("mail", "example.com")).toEqual({
      progress: "Verifying email DNS records for example.com...",
      done: "Email DNS records verified",
    });
  });

  test("returns dns labels matching the existing dnsVerified string", () => {
    expect(deployComponentLabels("dns", "example.com")).toEqual({
      progress: "Verifying DNS records for example.com...",
      done: "DNS verified for example.com.",
    });
  });

  test("returns ssl labels", () => {
    expect(deployComponentLabels("ssl", "example.com")).toEqual({
      progress: "Issuing SSL certificate for example.com...",
      done: "SSL certificate issued for example.com",
    });
  });
});

describe("deployStatusRetryMessage", () => {
  test("includes current retry count and countdown", () => {
    expect(deployStatusRetryMessage("Verifying DNS records for example.com...", 2, 5, 30)).toBe(
      "Verifying DNS records for example.com... 2/5 attempts, retrying in 30s",
    );
  });
});

describe("nextStepsBlock", () => {
  test("links directly to the production instance domain settings", () => {
    const output = nextStepsBlock("app_123", "ins_456");

    expect(output).toContain("View and manage domain configuration in the Clerk Dashboard");
    expect(output).toContain("https://dashboard.clerk.com/apps/app_123/instances/ins_456/domains");
  });
});

describe("pendingDnsRecords", () => {
  const targets: CnameTarget[] = [
    { host: "clerk.example.com", value: "frontend-api.clerk.services", required: true },
    { host: "accounts.example.com", value: "accounts.clerk.services", required: true },
    {
      host: "clkmail.example.com",
      value: "mail.example.com.nam1.clerk.services",
      required: true,
    },
  ];

  test("returns no records when only SSL remains pending", () => {
    expect(pendingDnsRecords(targets, { dns: true, ssl: false, mail: true })).toEqual([]);
  });

  test("returns only email records when email DNS remains pending", () => {
    const output = pendingDnsRecords(targets, { dns: true, ssl: true, mail: false }).join("\n");

    expect(output).toContain("clkmail.example.com");
    expect(output).not.toContain("clerk.example.com");
    expect(output).not.toContain("accounts.example.com");
  });

  test("returns non-email records when DNS remains pending", () => {
    const output = pendingDnsRecords(targets, { dns: false, ssl: true, mail: true }).join("\n");

    expect(output).toContain("clerk.example.com");
    expect(output).toContain("accounts.example.com");
    expect(output).not.toContain("clkmail.example.com");
  });
});

describe("dnsRecords", () => {
  test("labels DKIM CNAME records as email DNS records", () => {
    const output = dnsRecords([
      { host: "clk._domainkey.example.com", value: "dkim1.clerk.services", required: true },
      { host: "clk2._domainkey.example.com", value: "dkim2.clerk.services", required: true },
    ]).join("\n");

    expect(output).toContain("Email (Clerk handles SPF/DKIM automatically)");
    expect(output).not.toContain("\n  CNAME\n    Type:");
  });
});
