import { lstat, mkdir, readdir, unlink } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { CliError } from "../../../lib/errors.ts";
import type { FileAction, ScaffoldPlan } from "../frameworks/types.ts";

const SDK_VERSION = "1.1.7";
const KEY_PLACEHOLDER = "CLERK_DEVELOPMENT_PUBLISHABLE_KEY";
const GENERATED = "Generated by Clerk CLI";
const identifier = /^[A-Za-z][A-Za-z0-9_]*(?:\.[A-Za-z][A-Za-z0-9_]*)+$/;

export type AndroidOptions = {
  androidModule?: string;
  androidPackage?: string;
  androidFingerprint?: string[];
  dryRun?: boolean;
};
export type AndroidProject = {
  root: string;
  module: string;
  packageName: string;
  fingerprints: string[];
  plan: ScaffoldPlan;
  originals: Map<string, string | null>;
};

function unsupported(reason: string): never {
  throw new CliError(
    `${reason} No Android project files were changed. See https://clerk.com/docs/android/getting-started/quickstart for manual setup.`,
  );
}

export function normalizeFingerprints(values: string[]): string[] {
  return [
    ...new Set(
      values.map((value) => {
        const compact = value.trim().replaceAll(":", "");
        if (!/^[a-fA-F0-9]{64}$/.test(compact))
          throw new CliError(
            "--android-fingerprint must be a SHA-256 signing certificate fingerprint (64 hex digits, optionally separated by colons).",
          );
        return compact.toUpperCase().match(/../g)!.join(":");
      }),
    ),
  ].sort();
}

// Keep offsets stable while hiding comments and strings from structural scans.
export function maskCode(source: string, strings = true): string {
  return source.replace(
    /\/\*[\s\S]*?\*\/|\/\/[^\r\n]*|"""[\s\S]*?"""|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'/g,
    (text) => (!strings && !text.startsWith("/") ? text : text.replace(/[^\r\n]/g, " ")),
  );
}

function blocks(source: string, name: string): { open: number; close: number }[] {
  const masked = maskCode(source);
  const result = [];
  for (const match of masked.matchAll(new RegExp(`\\b${name}\\s*\\{`, "g"))) {
    const open = masked.indexOf("{", match.index);
    let depth = 1;
    let close = open;
    while (depth && ++close < masked.length) {
      if (masked[close] === "{") depth++;
      if (masked[close] === "}") depth--;
    }
    if (depth) unsupported("Unbalanced Kotlin/Gradle block.");
    result.push({ open, close });
  }
  return result;
}

function literal(source: string, name: string): string | undefined {
  const masked = maskCode(source);
  if ([...masked.matchAll(new RegExp(`\\b${name}\\b`, "g"))].length !== 1) return undefined;
  const matches = [
    ...source.matchAll(new RegExp(`\\b${name}\\s*(?:=\\s*)?["']([^"'\\r\\n]+)["']`, "g")),
  ].filter((match) => masked.slice(match.index, match.index + name.length) === name);
  if (matches.length !== 1) return undefined;
  const match = matches[0]!;
  const rest = maskCode(source.slice(match.index + match[0].length));
  if (!/^[ \t]*(?:$|[\r\n;}])/.test(rest)) return undefined;
  return match[1];
}

function hasCatalogSdk(build: string, catalog: string | null): boolean {
  if (!catalog) return false;
  const parsed = Bun.TOML.parse(catalog) as { libraries?: Record<string, unknown> };
  return Object.entries(parsed.libraries ?? {}).some(([alias, value]) => {
    const entry = value as { module?: string; group?: string; name?: string };
    const coordinate =
      typeof value === "string" ? value : (entry.module ?? `${entry.group}:${entry.name}`);
    const accessor = `libs.${alias.replace(/[-_]/g, ".")}`;
    return (
      /^com\.clerk:clerk-android-(api|ui)(:|$)/.test(coordinate) &&
      maskCode(build).includes(`implementation(${accessor})`)
    );
  });
}

async function assertSafePath(root: string, path: string): Promise<void> {
  const target = resolve(root, path);
  const rel = relative(root, target);
  if (!rel || rel.startsWith("..") || rel.startsWith("/"))
    unsupported(`Unsafe Android path: ${path}.`);
  let current = root;
  for (const part of rel.split("/")) {
    current = join(current, part);
    const stat = await lstat(current).catch((error: NodeJS.ErrnoException) => {
      if (error.code === "ENOENT") return null;
      throw error;
    });
    if (stat?.isSymbolicLink()) unsupported(`Android setup does not follow symlinks: ${path}.`);
  }
}

async function read(project: AndroidProject, path: string): Promise<string | null> {
  await assertSafePath(project.root, path);
  const file = Bun.file(join(project.root, path));
  const content = (await file.exists()) ? await file.text() : null;
  project.originals.set(path, content);
  return content;
}

function change(project: AndroidProject, path: string, content: string, description: string): void {
  const old = project.originals.get(path);
  if (old === content) return;
  project.plan.actions.push({
    type: old == null ? "create" : "modify",
    path,
    content,
    description,
  });
}

async function findModules(root: string): Promise<string[]> {
  const found: string[] = [];
  async function visit(dir: string, depth: number): Promise<void> {
    if (depth > 4) return;
    const entries = await readdir(join(root, dir), { withFileTypes: true });
    if (
      entries.some((entry) => entry.isFile() && /^build\.gradle(?:\.kts)?$/.test(entry.name)) &&
      (await Bun.file(join(root, dir, "src/main/AndroidManifest.xml")).exists())
    )
      found.push(dir || ".");
    for (const entry of entries) {
      if (
        entry.isDirectory() &&
        !entry.name.startsWith(".") &&
        !["build", "node_modules", "gradle"].includes(entry.name)
      ) {
        await visit(join(dir, entry.name), depth + 1);
      }
    }
  }
  await visit("", 0);
  return found;
}

// Kotlin 2.4 metadata in SDK 1.1.7 requires a compatible compiler. Keep the
// common version catalog / literal plugin layouts in sync; custom build logic
// and processor migrations need the project's owner to select compatible versions.
async function planKotlinToolchain(
  project: AndroidProject,
  modulePath: string,
  moduleBuild: string,
  catalog: string | null,
): Promise<string> {
  const minimum = "2.4.20";
  const rootPaths = ["build.gradle.kts", "build.gradle"].filter((path) => path !== modulePath);
  const sources = new Map<string, string>([[modulePath, moduleBuild]]);
  for (const path of rootPaths) {
    const source = await read(project, path);
    if (source != null) sources.set(path, source);
  }
  const all =
    [...sources.values()].map((source) => maskCode(source, false)).join("\n") + (catalog ?? "");
  const parsedPlugins = catalog
    ? (Bun.TOML.parse(catalog) as { plugins?: Record<string, { id?: string }> }).plugins
    : undefined;
  const appliesKotlin =
    /(?:org\.jetbrains\.kotlin\.android|kotlin-android|kotlin\s*\(\s*["']android["'])/.test(
      maskCode(moduleBuild, false),
    ) ||
    Object.entries(parsedPlugins ?? {}).some(
      ([alias, plugin]) =>
        plugin.id === "org.jetbrains.kotlin.android" &&
        maskCode(moduleBuild).includes(`libs.plugins.${alias.replace(/[-_]/g, ".")}`),
    );
  const agpVersion =
    /(?:com\.android\.application["']\s*\)\s+version\s+["']|^agp\s*=\s*["'])(\d+)\./m.exec(all);
  if (!appliesKotlin && !(agpVersion && Number(agpVersion[1]) >= 9))
    unsupported(
      "The selected module must apply the Kotlin Android plugin or use AGP 9 built-in Kotlin to compile the generated Application.",
    );
  const compatible = (version: string) => {
    const [major, minor] = version.split(".").map(Number);
    return major! > 2 || (major === 2 && minor! >= 4);
  };
  const pluginVersion =
    /(\b(?:id\s*\(\s*["']org\.jetbrains\.kotlin\.[\w.]+["']\s*\)|kotlin\s*\(\s*["'][\w.]+["']\s*\))\s+version\s+["'])(\d+\.\d+\.\d+)(["'])/g;
  const hasOldPlugin = [...all.matchAll(pluginVersion)].some((m) => !compatible(m[2]!));
  const parsedCatalog = catalog
    ? (Bun.TOML.parse(catalog) as { versions?: Record<string, string> })
    : null;
  const catalogMatch = parsedCatalog?.versions?.kotlin
    ? /^kotlin\s*=\s*["'](\d+\.\d+\.\d+)["']/m.exec(catalog!)
    : null;
  const oldCatalog = catalogMatch && !compatible(catalogMatch[1]!);
  if ((hasOldPlugin || oldCatalog) && /(?:ksp|kapt)/i.test(all))
    unsupported(
      "Upgrade Kotlin to 2.4+ and choose compatible KSP/kapt processor versions before adding Clerk SDK 1.1.7.",
    );
  if (oldCatalog) {
    change(
      project,
      "gradle/libs.versions.toml",
      catalog!.replace(catalogMatch[0], catalogMatch[0].replace(catalogMatch[1]!, minimum)),
      "Upgrade Kotlin and shared Kotlin plugin versions for Clerk SDK compatibility",
    );
  }
  let hasCompiler = Boolean(catalogMatch);
  for (const [path, source] of sources) {
    const visible = maskCode(source, false);
    const replacements = [...visible.matchAll(pluginVersion)];
    if (replacements.length) hasCompiler = true;
    let updated = source;
    for (const m of replacements.reverse()) {
      if (compatible(m[2]!)) continue;
      updated =
        updated.slice(0, m.index) + m[1] + minimum + m[3] + updated.slice(m.index + m[0].length);
    }
    if (path === modulePath) moduleBuild = updated;
    else
      change(project, path, updated, "Upgrade Kotlin plugin versions for Clerk SDK compatibility");
  }
  if (!hasCompiler) {
    const classpathVersion = /org\.jetbrains\.kotlin:kotlin-gradle-plugin:(\d+\.\d+\.\d+)/.exec(
      all,
    );
    if (classpathVersion && compatible(classpathVersion[1]!)) return moduleBuild;
    // AGP 9's built-in Kotlin can be upgraded by adding KGP to the root classpath.
    const agp =
      /(?:com\.android\.application["']\s*\)\s+version\s+["']|^agp\s*=\s*["'])(\d+)\./m.exec(all);
    const rootPath = [...sources.keys()].find((path) => rootPaths.includes(path));
    if (!classpathVersion && agp && Number(agp[1]) >= 9 && rootPath && !/ksp|kapt/i.test(all)) {
      const prefix = `buildscript {\n    repositories { mavenCentral() }\n    dependencies { classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${minimum}") }\n}\n\n`;
      const rootSource = sources.get(rootPath)!;
      const imports = [...maskCode(rootSource, false).matchAll(/^import[^\r\n]*[\r\n]+/gm)];
      const lastImport = imports.at(-1);
      const at = lastImport ? lastImport.index + lastImport[0].length : 0;
      change(
        project,
        rootPath,
        rootSource.slice(0, at) + prefix + rootSource.slice(at),
        "Use Kotlin 2.4 with AGP's built-in Kotlin for Clerk SDK compatibility",
      );
    } else {
      unsupported(
        "Cannot verify a compatible Kotlin compiler. Declare Kotlin 2.4+ in the root plugins block or the kotlin version-catalog entry before automatic setup.",
      );
    }
  }
  return moduleBuild;
}

export async function inspectAndroidProject(
  root: string,
  options: AndroidOptions = {},
): Promise<AndroidProject> {
  const fingerprints = normalizeFingerprints(options.androidFingerprint ?? []);
  if (options.androidPackage && !identifier.test(options.androidPackage))
    unsupported(
      "Invalid --android-package. Use the installed application's applicationId, including any variant suffix.",
    );
  const modules = options.androidModule ? [options.androidModule] : await findModules(root);
  if (modules.length !== 1)
    unsupported("Select one Android application module with --android-module <relative-path>.");
  const module = modules[0]!;
  const project: AndroidProject = {
    root: resolve(root),
    module,
    packageName: "",
    fingerprints,
    plan: { actions: [], postInstructions: [] },
    originals: new Map(),
  };
  const kotlinBuild = join(module, "build.gradle.kts");
  const groovyBuild = join(module, "build.gradle");
  const kts = await read(project, kotlinBuild);
  const groovy = await read(project, groovyBuild);
  if ((kts == null) === (groovy == null))
    unsupported("Expected exactly one build.gradle.kts or build.gradle in the selected module.");
  const buildPath = kts != null ? kotlinBuild : groovyBuild;
  const build = (kts ?? groovy)!;
  const android = blocks(build, "android");
  const config = blocks(build, "defaultConfig");
  if (
    android.length !== 1 ||
    config.length !== 1 ||
    config[0]!.open < android[0]!.open ||
    config[0]!.close > android[0]!.close
  )
    unsupported("Cannot locate a single android.defaultConfig block.");
  const namespace = literal(build.slice(android[0]!.open, android[0]!.close), "namespace");
  if (!namespace || !identifier.test(namespace))
    unsupported("Android namespace must be a literal package name for automatic Kotlin setup.");
  const defaultConfig = build.slice(config[0]!.open, config[0]!.close);
  const packageName = options.androidPackage ?? literal(defaultConfig, "applicationId");
  const masked = maskCode(build);
  if (
    !options.androidPackage &&
    (/\b(?:applicationIdSuffix|productFlavors|apply|androidComponents)\b/.test(masked) ||
      [...masked.matchAll(/\bapplicationId\b/g)].length !== 1)
  )
    unsupported(
      "This build customizes its application ID or applies external build logic. Pass --android-package with the final applicationId for the installed variant.",
    );
  if (!packageName || !identifier.test(packageName))
    unsupported(
      "Cannot determine the Android applicationId. Pass --android-package explicitly; the Gradle namespace is not the applicationId.",
    );
  project.packageName = packageName;
  let updatedBuild = build;
  const catalog = await read(project, "gradle/libs.versions.toml");
  const minSdkMatch =
    /\bminSdk(?:Version)?\s*(?:=\s*)?(\d+|libs\.versions\.([\w.]+)\.get\(\)\.toInt\(\))/.exec(
      maskCode(defaultConfig),
    );
  const versions = catalog
    ? (Bun.TOML.parse(catalog) as { versions?: Record<string, string> }).versions
    : undefined;
  const minSdk = minSdkMatch?.[2]
    ? versions?.[minSdkMatch[2].replaceAll(".", "-")]
    : minSdkMatch?.[1];
  if (!minSdkMatch || !minSdk || !/^\d+$/.test(minSdk))
    unsupported(
      "Set a literal or version-catalog minSdk of at least 24 in defaultConfig before automatic Android setup.",
    );
  if (Number(minSdk) < 24) {
    const index = config[0]!.open + minSdkMatch.index;
    updatedBuild =
      updatedBuild.slice(0, index) +
      minSdkMatch[0].replace(minSdkMatch[1]!, "24") +
      updatedBuild.slice(index + minSdkMatch[0].length);
  }
  // A pre-existing Clerk dependency may be a catalog alias or local project.
  const hasClerk =
    /\bimplementation\s*\(?\s*["']com\.clerk:clerk-android-(?:api|ui):/.test(
      maskCode(build, false),
    ) || hasCatalogSdk(build, catalog);
  if (catalog?.includes("com.clerk") && !hasClerk)
    project.plan.postInstructions.push(
      "Check any existing Clerk version-catalog entry; this setup adds a direct SDK dependency.",
    );
  if (!hasClerk) {
    const deps = blocks(updatedBuild, "dependencies").filter((block) => {
      const prefix = maskCode(updatedBuild.slice(0, block.open));
      return (
        [...prefix].filter((c) => c === "{").length === [...prefix].filter((c) => c === "}").length
      );
    });
    const dependency = `\n    implementation("com.clerk:clerk-android-api:${SDK_VERSION}")`;
    if (deps.length > 1)
      unsupported("Multiple top-level dependencies blocks require manual SDK installation.");
    updatedBuild = deps[0]
      ? updatedBuild.slice(0, deps[0].open + 1) + dependency + updatedBuild.slice(deps[0].open + 1)
      : updatedBuild + `\n\ndependencies {${dependency}\n}\n`;
  }
  updatedBuild = await planKotlinToolchain(project, buildPath, updatedBuild, catalog);
  change(project, buildPath, updatedBuild, "Install the Clerk API SDK and require minSdk 24+");

  const manifestPath = join(module, "src/main/AndroidManifest.xml");
  const manifest = await read(project, manifestPath);
  if (!manifest || /<!DOCTYPE|<!ENTITY/.test(manifest))
    unsupported("A standard AndroidManifest.xml is required.");
  const xml = manifest.replace(/<!--[\s\S]*?-->/g, (comment) => " ".repeat(comment.length));
  if (!/xmlns:android\s*=\s*["']http:\/\/schemas.android.com\/apk\/res\/android["']/.test(xml))
    unsupported("AndroidManifest.xml must declare the android XML namespace.");
  const apps = [...xml.matchAll(/<application\b[^>]*>/g)];
  if (apps.length !== 1)
    unsupported("Expected a single application element in AndroidManifest.xml.");
  const app = apps[0]!;
  const nameMatch = /android:name\s*=\s*["']([^"']+)["']/.exec(app[0]);
  const appName = nameMatch?.[1];
  if (appName && !/^\.?[\w.]+$/.test(appName))
    unsupported("The manifest Application class must be a literal Kotlin class name.");
  const className = appName
    ? appName.startsWith(".")
      ? namespace + appName
      : appName.includes(".")
        ? appName
        : `${namespace}.${appName}`
    : `${namespace}.ClerkApplication`;
  const sourcePath = className.replaceAll(".", "/") + ".kt";
  const kotlinPath = join(module, "src/main/kotlin", sourcePath);
  const javaPath = join(module, "src/main/java", sourcePath);
  const kotlin = await read(project, kotlinPath);
  const java = await read(project, javaPath);
  if (kotlin != null && java != null)
    unsupported("Duplicate Kotlin Application classes require manual setup.");
  const source = kotlin ?? java;
  const path = java != null ? javaPath : kotlinPath;
  if (!appName && source != null)
    unsupported(
      `The unregistered ${className} source already exists. Register it in the manifest before running init.`,
    );
  const init = `com.clerk.api.Clerk.initialize(this, publishableKey = getString(${namespace}.R.string.clerk_publishable_key))`;
  if (source == null) {
    if (appName)
      unsupported(
        `Cannot find Kotlin source for ${className}. Initialize Clerk in the existing Application manually.`,
      );
    change(
      project,
      path,
      `package ${namespace}\n\nimport android.app.Application\n\n// ${GENERATED}\nclass ClerkApplication : Application() {\n    override fun onCreate() {\n        super.onCreate()\n        ${init}\n    }\n}\n`,
      "Initialize Clerk when the Android application starts",
    );
  } else if (maskCode(source).includes(init)) {
    // Our generated runtime sink already exists. Only the key resource may need work.
  } else {
    if (/\bClerk\s*\.\s*(?:initialize|configure)\b/.test(source))
      unsupported(
        "This Application already configures Clerk. Keep its existing initialization and configure native registration manually.",
      );
    const onCreates = [...maskCode(source).matchAll(/\boverride\s+fun\s+onCreate\s*\(\s*\)\s*\{/g)];
    const supers = [...maskCode(source).matchAll(/\bsuper\.onCreate\(\)/g)];
    if (onCreates.length !== 1 || supers.length !== 1 || supers[0]!.index < onCreates[0]!.index)
      unsupported(
        "Automatic setup requires a Kotlin Application with one onCreate override calling super.onCreate().",
      );
    const end = supers[0]!.index + supers[0]![0].length;
    if (!/^[ \t]*(?:$|[\r\n;}])/.test(maskCode(source.slice(end))))
      unsupported("The Application super.onCreate call must be a standalone statement.");
    change(
      project,
      path,
      source.slice(0, end) + `\n        ${init}` + source.slice(end),
      "Initialize Clerk after Application.onCreate",
    );
  }
  let nextManifest = manifest;
  if (!appName) {
    const at = app.index + "<application".length;
    nextManifest = manifest.slice(0, at) + ` android:name="${className}"` + manifest.slice(at);
  }
  if (!/<uses-permission\b[^>]*android:name\s*=\s*["']android.permission.INTERNET["']/.test(xml)) {
    nextManifest = nextManifest.replace(
      /(<manifest\b[^>]*>)/,
      '$1\n    <uses-permission android:name="android.permission.INTERNET" />',
    );
  }
  change(
    project,
    manifestPath,
    nextManifest,
    "Register the Application class and internet permission",
  );
  const resourcePath = join(module, "src/main/res/values/clerk.xml");
  const resource = await read(project, resourcePath);
  if (
    resource != null &&
    (!resource.includes(`<!-- ${GENERATED} -->`) ||
      [...resource.matchAll(/<string\b/g)].length !== 1 ||
      !/<string name="clerk_publishable_key" translatable="false">pk_test_[A-Za-z0-9+/=_-]+<\/string>/.test(
        resource,
      ))
  )
    unsupported(`${resourcePath} already exists and is not managed by Clerk.`);
  for await (const path of new Bun.Glob(`${module}/src/**/res/values*/*.xml`).scan({
    cwd: project.root,
    onlyFiles: true,
    followSymlinks: false,
  })) {
    if (path === resourcePath) continue;
    const value = await read(project, path);
    if (/name\s*=\s*["']clerk_publishable_key["']/.test(value ?? ""))
      unsupported(
        `A clerk_publishable_key resource already exists in ${path}. Preserve it and initialize Clerk manually.`,
      );
  }
  change(
    project,
    resourcePath,
    `<?xml version="1.0" encoding="utf-8"?>\n<resources>\n    <!-- ${GENERATED} -->\n    <string name="clerk_publishable_key" translatable="false">${KEY_PLACEHOLDER}</string>\n</resources>\n`,
    "Configure the development publishable key (no secret key)",
  );
  project.plan.postInstructions.push(
    "Sync Gradle with Java 17 or newer, then build and run the app. The Clerk API SDK is initialized; add your authentication UI using the Android quickstart.",
  );
  if (!fingerprints.length)
    project.plan.postInstructions.push(
      "Pass --android-fingerprint <SHA-256> from ./gradlew signingReport to enable passkey association. Include the certificate used to sign the installed app.",
    );
  return project;
}

export function withPublishableKey(project: AndroidProject, key: string): AndroidProject {
  if (!/^pk_test_[A-Za-z0-9+/=_-]+$/.test(key))
    throw new CliError("Android init requires a development publishable key.");
  return {
    ...project,
    plan: {
      ...project.plan,
      actions: project.plan.actions.flatMap((action): FileAction[] => {
        if (action.type === "skip") return [action];
        const content = action.content.replace(KEY_PLACEHOLDER, key);
        return content === project.originals.get(action.path) ? [] : [{ ...action, content }];
      }),
    },
  };
}

export async function assertProjectUnchanged(project: AndroidProject): Promise<void> {
  for (const [path, original] of project.originals) {
    await assertSafePath(project.root, path);
    const file = Bun.file(join(project.root, path));
    const current = (await file.exists()) ? await file.text() : null;
    if (current !== original)
      throw new CliError(
        `Android setup stopped because ${path} changed after inspection. Run init again.`,
      );
  }
}

export async function applyAndroidProject(project: AndroidProject): Promise<void> {
  await assertProjectUnchanged(project);
  const written: Exclude<FileAction, { type: "skip" }>[] = [];
  try {
    for (const action of project.plan.actions) {
      if (action.type === "skip") continue;
      await assertSafePath(project.root, action.path);
      const path = join(project.root, action.path);
      await mkdir(dirname(path), { recursive: true });
      written.push(action);
      await Bun.write(path, action.content);
    }
  } catch (error) {
    for (const action of written.reverse()) {
      await assertSafePath(project.root, action.path);
      const file = Bun.file(join(project.root, action.path));
      if ((await file.exists()) && (await file.text()) === action.content) {
        const original = project.originals.get(action.path);
        if (original == null) await unlink(join(project.root, action.path));
        else await Bun.write(file, original);
      }
    }
    throw error;
  }
}
